# Generated by Django 3.1.3 on 2021-02-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0003_auto_20210204_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
