# Generated by Django 3.1.3 on 2021-02-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0005_auto_20210204_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_maker.person', unique=True),
        ),
    ]
