# Generated by Django 3.1.3 on 2021-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0008_auto_20210204_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
