# Generated by Django 3.1.3 on 2021-02-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0011_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=150)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_maker.person')),
            ],
        ),
    ]
