# Generated by Django 3.1.1 on 2021-02-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0012_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
