# Generated by Django 3.1.3 on 2021-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0016_auto_20210224_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
