# Generated by Django 3.1.1 on 2021-02-27 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0017_auto_20210225_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(default=django.utils.timezone.now, max_length=270),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
